### ISSUE TITLE
Extensions dont download 

### ISSUE THREAD

**Issue by AdrianJack** [jobobby04/ShosetsuExtensions#4]
The extensions fannovel wuxiap don't download at all.
Error notification comes up.
![Screenshot_20240212_205018_Shosetsu](https://github.com/jobobby04/ShosetsuExtensions/assets/139681740/b1c53cc8-2cdf-404f-8af3-afdf6b4d7b63)

**Comment by jobobby04** [comment]
Man I'm dumb. Found the issue and its now fixed
