### ISSUE TITLE
Can you add FansMTL?

### ISSUE THREAD

**Issue by TheFirstProgenitor** [jobobby04/ShosetsuExtensions#5]
Same as Readwn and Fannovel.
Theres difference in content i.e. chapters are more for many titles and they have some titles that readwn and the rest dont have.
Me cloning this repo worked but bugs show up after few days after which i have to create new repo change ids and add extensions(cant remove old bugging extensions as whole app closes when selecting the extension).
Would be great if you could add it...
Peace...
![Screenshot_20240413_230743_Shosetsu](https://github.com/jobobby04/ShosetsuExtensions/assets/166703522/f80a8da0-e549-4588-9671-648c974b6a12)

**Comment by jobobby04** [comment]
Sure, I've been meaning to go and add all the ReadWN clones I know of

**Comment by jobobby04** [comment]
Looks like one of the sites turned into FansMTL as well

**Comment by jobobby04** [comment]
Done
