### ISSUE TITLE
Can you add icons for the extensions?

### ISSUE THREAD

**Issue by AdrianJack** [jobobby04/ShosetsuExtensions#7]
This repo one i cloned from yours has icons for fanno,readwn,wuxiam8(lightnovemeta),fansmtl and so.
https://github.com/LordGrindelwald/ShosetsuExtensions/tree/main/icons
If you can add icons i can create the rest 4 u if you're busy. 
Peace... ✌🏻

**Comment by LordGrindelwald** [comment]
![WuxiaFox](https://github.com/jobobby04/ShosetsuExtensions/assets/164880317/45962030-740d-437a-839b-363cbb5eef0e)
![LTNovel](https://github.com/jobobby04/ShosetsuExtensions/assets/164880317/9f2b27d7-3c3e-41bd-9844-8ea42507bbee)
![LightnovelMeta](https://github.com/jobobby04/ShosetsuExtensions/assets/164880317/f61a7143-dcf9-4b92-9a2e-7c56575228d2)
![FanNovel](https://github.com/jobobby04/ShosetsuExtensions/assets/164880317/9654b91a-4f38-421e-968b-c5fa75296520)
![FansMTL](https://github.com/jobobby04/ShosetsuExtensions/assets/164880317/f838c3e0-f990-4c61-8db0-a653b4ea15cd)
![ReadWN](https://github.com/jobobby04/ShosetsuExtensions/assets/164880317/16fb7eda-aa6e-494f-bd78-7bef27c04e70)
![Wuxiamate](https://github.com/jobobby04/ShosetsuExtensions/assets/164880317/492eed9a-0f6f-4f33-adb8-f46e9c3dde1e)

**Comment by LordGrindelwald** [comment]
Some have same icon.

**Comment by jobobby04** [comment]
Done
