### ISSUE TITLE
Extensions need update

### ISSUE THREAD

**Issue by AdrianJack** [jobobby04/ShosetsuExtensions#8]
Readwn and Fannovel work but tge search is broken as the sutes have changed domain names or stg.
Readwn is wuxia box for now and fannovel is fannovels.
Search workswhen extensions are updated i.e. links in code are changed from prev to new...
Peace...✌🏻

**Comment by jobobby04** [comment]
Hmm, I see. I'll delete the new WuxiaBox extension and then move ReadWN to WuxiaBox urls

**Comment by LordGrindelwald** [comment]
Wuxiap redirects to wuxiabox too

**Comment by jobobby04** [comment]
Hmm, I'll delete Wuxiap then

**Comment by LordGrindelwald** [comment]
Lightnovel meta redirects to wuxiamate(just found out)

**Comment by LordGrindelwald** [comment]
Bro can you just comment when you're done updating all of the extensions.
I just wanna remove the repo i created and add this one.
P.S. I'm here cuz i don't know nothing about coding.
Please don't mind.

**Comment by jobobby04** [comment]
Done
